Initiated dynamic programming
GDSCNITD/DSA101 pull request #6
Opened 2022-01-25 18:35 UTC by umangkumarr

2022-01-26 07:24 UTC, Blakeinstein requested changes

2022-01-26 07:24 UTC, Blakeinstein commented on problems/Dynamic Programming/LIS.md
> +---
File name should be `01-Longest-increasing-sequence.md`

2022-01-26 07:24 UTC, Blakeinstein commented on problems/Dynamic Programming/LIS.md
> +sidebar_position: 2
position is 1, since its the first problem in the category.

2022-01-26 07:24 UTC, Blakeinstein commented on problems/Dynamic Programming/LIS.md
> +```cpp
Should we put this in a spoiler? Try this https://stackoverflow.com/questions/60827828/docusaurus-v2-collapsible-section-in-markdown

2022-01-26 10:32 UTC, umangkumarr commented
Requested changes added.

2022-01-26 13:42 UTC, Blakeinstein commented on problems/Dynamic Programming/01-Longest-Increasing-Sequence.md
> +<details><summary>C++ Code</summary>
Summary should be something like Hidden - Click to view.

The spoiler should include the whole solution, with the explanation.

2022-01-26 13:43 UTC, Blakeinstein requested changes
I think we should hide the solution from being visible and the user needs to opt in. What do you think?

2022-01-27 18:57 UTC, Blakeinstein approved these changes

2022-01-27 18:57 UTC, merged

2022-01-27 18:58 UTC, Blakeinstein commented
@all-contibutors add @umangkumarr for content

2022-01-27 18:58 UTC, Blakeinstein commented
@all-contributors please add @umangkumarr for content